---
title: "contributing"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### issues

Open an 'issue' for a bug report, error or feature request (i.e., user-facing issues).

If you're certain that you've found a typo or error (e.g., misspelled road names), consider submitting a 'pull request'. If you're uncertain, just open an 'issue'.

If you're reporting a bug, include a reproducible example: 1) describe what you expected to get and what you actually got and 2) provide the expression or snippet of code that will generate the error (please do not include the entire script of your workflow).

### pull requests

Submit a 'pull request' to propose a specific "under the hood" fix for the problem in the source code.

This can include typos or errors (see above), as well as issues of coding or implementation. Please be aware that this package is under development. So while I strive to ensure that the code always works, the implementation may not always be optimal in terms of speed or elegance.
